version: "3.9"
   
services:
  db:
    build: ../postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5001:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  tileservergl:
    build: ../tileservergl
    volumes:
      - ../tileservergl/tldata:/data
    ports:
      - 8080:8080
    command: "--verbose -c /data/config1.json"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/djangoserver
    ports:
      - 8000:8000
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
volumes:
  pgdata:
