# Generated by Django 4.1.7 on 2023-03-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('category', models.TextField()),
                ('date', models.DateField()),
                ('image', models.TextField(default='../static/images/default-card.png')),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
    ]
